pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    echo "I am in build step"
                    chmod +x ./gradlew
                    ./gradlew build
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            environment {
                SONAR_SCANNER_OPTS = "-Xmx2g"
            }
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                    mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dlicense.skip=true
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage ="
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Pubishing DockerImage ="
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
	post{
		always{
		deleteDir()
        }
    }
}