pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    echo "I am in build step"
                    chmod +x ./gradlew
                    ./gradlew build
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                  sh script: '''
                     echo "I am in sonarqube step"
                  ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage ="
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                    echo "I am Pubishing DockerImage"
                    sh "docker tag cd14cecfdb3a pixel238/firsttry"
                    sh "docker push pixel238/firsttry:latest"
            }
        }
    }
	post{
		always{
		deleteDir()
        }
    }
}